#Task 2 - Superstore_USA
1. load this data in sql and in pandas with a relation in sql 
2. while loading this data you dont have to create a table manually you can use any automated approach to create a table and   
   load a data in bulk in table 
3. Find out how return that we have recived and with a product id 
4. try  to join order and return data both in sql and pandas 
5. Try to find out how many unique customer that we have 
6. try to find out in how many regions we are selling a product and who is a manager for a respective region 
7. find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode 
   with respect to dataset 
8. Create a new coulmn and try to find our a diffrence between order date and shipment date
9. base on question number 8 find out for which order id we have shipment duration more than 10 days 
10. Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as 
    well 
11. Gorup by region and find out which region is more profitable 
12. Try to find out overalll in which country we are giving more didscount 
13. Give me a list of unique postal code 
14. which customer segement is more profitalble find it out . 
15. try to find out the 10th most loss making product catagory . 
16. Try to find out 10 top  product with highest margins

In [3]:
import pandas as pd
import mysql.connector as mysql
import logging
from mysql.connector import Error
import pymysql
import os
from sqlalchemy import create_engine

In [4]:
#Task2- qstn1-Database creation

def database_creation():
    try:
        mydb = mysql.connect(host = "localhost" , user ="root" , passwd = "Hannah_0027" )
        if mydb.is_connected():
            cursor = mydb.cursor()
            cursor.execute("CREATE DATABASE if not exists store_usa")
            print("Database is created")
    except Exception as e:
         print("Error while connecting to MySQL...", e)
database_creation()

Database is created

In [37]:
# Qstn 2-Create table and insert values into the table[while creting a table in mysql dont use manual approach to create it  ,always use a automation to create a table in mysql]

engine = create_engine('mysql+pymysql://root:Hannah_0027@localhost/store_usa')
order = pd.read_csv(r'C:\Users\ASUS\Desktop\code\data science\task\task\Superstore_USA.csv')

order.to_sql('super_store_usa', con=engine)

In [38]:
order

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,28-05-2012,30-05-2012,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,07-07-2010,08-07-2010,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,27-07-2011,28-07-2011,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,27-07-2011,28-07-2011,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,27-07-2011,27-07-2011,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,14-05-2013,15-05-2013,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,14-05-2013,14-05-2013,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,12-09-2013,14-09-2013,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,08-02-2010,11-02-2010,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,12-09-2013,14-09-2013,78.062400,23,172.48,87533

In [39]:
order.dtypes

Row ID                    int64
Order Priority           object
Discount                float64
Unit Price              float64
Shipping Cost           float64
Customer ID               int64
Customer Name            object
Ship Mode                object
Customer Segment         object
Product Category         object
Product Sub-Category     object
Product Container        object
Product Name             object
Product Base Margin     float64
Region                   object
State or Province        object
City                     object
Postal Code               int64
Order Date               object
Ship Date                object
Profit                  float64
Quantity ordered new      int64
Sales                   float64
Order ID                  int64
dtype: object

In [41]:
order.dtypes

Row ID                    int64
Order Priority           object
Discount                float64
Unit Price              float64
Shipping Cost           float64
Customer ID               int64
Customer Name            object
Ship Mode                object
Customer Segment         object
Product Category         object
Product Sub-Category     object
Product Container        object
Product Name             object
Product Base Margin     float64
Region                   object
State or Province        object
City                     object
Postal Code               int64
Order Date               object
Ship Date                object
Profit                  float64
Quantity ordered new      int64
Sales                   float64
Order ID                  int64
dtype: object

In [62]:
# Qstn3- Find out how return that we have recived and with a product id 

a = pd.ExcelFile(r'C:\Users\ASUS\Desktop\code\data science\task\task\Superstore_USA.xlsx')
returns = pd.read_excel(a, 'Returns',names = ["Order ID","Status"])
users = pd.read_excel(a, 'Users')

In [63]:
returns

      Order ID    Status
0           65  Returned
1          612  Returned
2          614  Returned
3          678  Returned
4          710  Returned
...        ...       ...
1629    182681  Returned
1630    182683  Returned
1631    182750  Returned
1632    182781  Returned
1633    182906  Returned

[1634 rows x 2 columns]

In [64]:
order_returns = pd.merge(order, returns)

In [65]:
merged_table= pd.DataFrame(order_returns)

In [66]:
merged_table

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status
0,1359,Low,0.05,5.85,2.27,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,...,New York,New York City,10012,20-04-2011,24-04-2011,-6.8200,9,54.79,9895,Returned
1,1950,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Washington,Seattle,98103,04-04-2010,06-04-2010,112.0600,47,228.46,13959,Returned
2,1951,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,...,Washington,Seattle,98103,04-04-2010,06-04-2010,16.7900,19,77.61,13959,Returned
3,5055,High,0.02,3.28,5.00,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Washington,Seattle,98103,16-08-2013,18-08-2013,-89.0600,52,190.52,36038,Returned
4,5573,Low,0.02,11.97,5.81,272,Eleanor Swain,Regular Air,Small Business,Office Supplies,...,North Carolina,Charlotte,28204,12-08-2013,12-08-2013,-81.9413,76,912.06,39490,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,986,Not Specified,0.06,37.94,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,California,Los Angeles,90061,04-01-2013,06-01-2013,-33.9680,3,113.14,7107,Returned
94,987,Not Specified,0.10,55.29,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,California,Los Angeles,90061,04-01-2013,05-01-2013,163.1200,35,1886.52,7107,Returned
95,6041,Medium,0.05,4.28,6.18,3075,Gordon Brandt,Express Air,Corporate,Office Supplies,...,California,Los Angeles,90061,25-06-2013,27-06-2013,-22.5600,12,73.71,42823,Returned
96,1910,High,0.05,14.48,1.99,3079,Andrew Levine,Regular Air,Consumer,Technology,...,Pennsylvania,Philadelphia,19112,30-09-2012,02-10-2012,165.2000,96,1337.67,13638,Returned
97,6625,High,0.06,128.24,12.65,3251,Peter Brooks,Regular Air,Small Business,Furniture,...,New York,New York City,10112,11-09-2012,13-09-2012,1844.9600,92,12002.16,47109,Returned

In [67]:
merged_table[(merged_table['Status']=='Returned')]['Order ID']

0      9895
1     13959
2     13959
3     36038
4     39490
      ...
93     7107
94     7107
95    42823
96    13638
97    47109
Name: Order ID, Length: 98, dtype: int64

In [70]:
 #Qstn 4 -Try  to join order and return data both in sql and pandas
    
pd.merge(order, returns)

#select * from returns JOIN super_store_usa ON super_store_usa.Order ID=returns.order ID;

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status
0,1359,Low,0.05,5.85,2.27,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,...,New York,New York City,10012,20-04-2011,24-04-2011,-6.8200,9,54.79,9895,Returned
1,1950,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Washington,Seattle,98103,04-04-2010,06-04-2010,112.0600,47,228.46,13959,Returned
2,1951,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,...,Washington,Seattle,98103,04-04-2010,06-04-2010,16.7900,19,77.61,13959,Returned
3,5055,High,0.02,3.28,5.00,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Washington,Seattle,98103,16-08-2013,18-08-2013,-89.0600,52,190.52,36038,Returned
4,5573,Low,0.02,11.97,5.81,272,Eleanor Swain,Regular Air,Small Business,Office Supplies,...,North Carolina,Charlotte,28204,12-08-2013,12-08-2013,-81.9413,76,912.06,39490,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,986,Not Specified,0.06,37.94,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,California,Los Angeles,90061,04-01-2013,06-01-2013,-33.9680,3,113.14,7107,Returned
94,987,Not Specified,0.10,55.29,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,California,Los Angeles,90061,04-01-2013,05-01-2013,163.1200,35,1886.52,7107,Returned
95,6041,Medium,0.05,4.28,6.18,3075,Gordon Brandt,Express Air,Corporate,Office Supplies,...,California,Los Angeles,90061,25-06-2013,27-06-2013,-22.5600,12,73.71,42823,Returned
96,1910,High,0.05,14.48,1.99,3079,Andrew Levine,Regular Air,Consumer,Technology,...,Pennsylvania,Philadelphia,19112,30-09-2012,02-10-2012,165.2000,96,1337.67,13638,Returned
97,6625,High,0.06,128.24,12.65,3251,Peter Brooks,Regular Air,Small Business,Furniture,...,New York,New York City,10112,11-09-2012,13-09-2012,1844.9600,92,12002.16,47109,Returned

In [87]:
#Qstn 5 -Try to find out how many unique customer that we have 

total = order['Customer ID'].unique()
print(" Number of unique customers:", len(total))

 Number of unique customers: 2703

In [ ]:
# sql guerry for qstn 5
cursor = mydb.cursor()
cursor.execute("select count(distinct Customer ID) from super_store_usa;") 
print(cursor.fetchall())
cursor.close()

In [101]:
#Qstn 6 -Try to find out in how many regions we are selling a product and who is a manager for a respective region 

users

    Region  Manager
0  Central    Chris
1     East     Erin
2    South      Sam
3     West  William

In [90]:
len(order['Region'].unique())

4

In [129]:
# Qstn 6 -Find out how many different shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset

shipment = order['Ship Mode']

In [103]:
type(shipment)

pandas.core.series.Series

In [126]:
s = pd.Series(shipment).value_counts()
print("Different shipment modes are : ",s)

Different shipment modes are :  Regular Air       7036
Delivery Truck    1283
Express Air       1107
Name: Ship Mode, dtype: int64

In [130]:
ship = pd.DataFrame(s)

In [131]:
shipment_total = pd.Series(shipment).count()
print(shipment_total)

9426

In [119]:
((ship [['Ship Mode']])/shipment_total)*100

                Ship Mode
Regular Air     74.644600
Delivery Truck  13.611288
Express Air     11.744112

In [141]:
order

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,difference_date
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525,2 days
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2010-07-07,2010-08-07,4.560000,4,13.01,88522,31 days
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523,1 days
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523,1 days
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532,1 days
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532,0 days
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,West Virginia,Charleston,25314,2013-12-09,2013-09-14,-1225.029097,4,2215.93,87533,-86 days
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,Wyoming,Cheyenne,82001,2010-08-02,2010-11-02,349.485000,5,506.50,87530,92 days
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,Wyoming,Cheyenne,82001,2013-12-09,2013-09-14,78.062400,23,172.48,87533,-86 days

In [138]:
order['Ship Date'] = pd.to_datetime(df['Ship Date'])
order['Order Date'] = pd.to_datetime(df['Order Date'])
order.dtypes

Row ID                           int64
Order Priority                  object
Discount                       float64
Unit Price                     float64
Shipping Cost                  float64
Customer ID                      int64
Customer Name                   object
Ship Mode                       object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Container               object
Product Name                    object
Product Base Margin            float64
Region                           int64
State or Province               object
City                            object
Postal Code                      int64
Order Date              datetime64[ns]
Ship Date               datetime64[ns]
Profit                         float64
Quantity ordered new             int64
Sales                          float64
Order ID                         int64
dtype: object

In [153]:
#Qstn 8 - Create a new coulmn and try to find our a diffrence between order date and shipment date

order["difference_date"] =  order['Ship Date'] - order['Order Date'] 
order["difference_date"]

0        2 days
1       31 days
2        1 days
3        1 days
4        0 days
         ...
9421     1 days
9422     0 days
9423   -86 days
9424    92 days
9425   -86 days
Name: difference_date, Length: 9426, dtype: timedelta64[ns]

In [168]:
order[(order['difference_date'].dt.components['days']>10)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,difference_date
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2010-07-07,2010-08-07,4.560000,4,13.01,88522,31 days
5,23597,Medium,0.09,55.48,14.30,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-09-11,2011-11-11,1388.052300,37,2011.67,88524,61 days
6,25549,Low,0.08,120.97,26.30,3,Bonnie Potter,Delivery Truck,Corporate,Technology,...,Washington,Anacortes,98221,2013-01-07,2013-08-07,1001.445300,12,1451.37,88526,212 days
16,22241,Critical,0.06,15.57,1.39,10,Meredith Norris Thomas,Regular Air,Home Office,Office Supplies,...,New Jersey,Pennsauken,8109,2011-04-10,2011-05-10,142.795500,14,206.95,90195,30 days
24,18181,Critical,0.00,4.42,4.99,15,Timothy Reese,Regular Air,Small Business,Office Supplies,...,New York,Smithtown,11787,2010-08-04,2010-09-04,-59.820000,7,33.47,86837,31 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9405,21952,Not Specified,0.05,10.91,2.99,3397,Andrea Shaw,Regular Air,Corporate,Office Supplies,...,Illinois,Danville,61832,2013-09-07,2013-11-07,-11.673144,1,12.48,87547,61 days
9406,22599,Critical,0.01,177.98,0.99,3398,Marc McDaniel,Regular Air,Corporate,Office Supplies,...,Illinois,Decatur,62521,2011-07-05,2011-09-05,902.106000,7,1307.40,87538,62 days
9415,26043,Not Specified,0.06,30.98,6.50,3400,Florence Gold,Regular Air,Corporate,Technology,...,West Virginia,Fairmont,26554,2012-04-07,2012-07-07,-113.600000,3,96.79,87540,91 days
9419,24912,Medium,0.05,35.99,1.25,3400,Florence Gold,Regular Air,Small Business,Technology,...,West Virginia,Fairmont,26554,2013-04-10,2013-05-10,411.481500,19,596.35,87549,30 days
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,Wyoming,Cheyenne,82001,2010-08-02,2010-11-02,349.485000,5,506.50,87530,92 days

In [181]:
#Qstn 9 - Based on Question number 8, find out for which order id we have shipment duration more than 10 day

order[(order['difference_date'].dt.components['days']>15)]['Order ID']

1       88522
5       88524
6       88526
16      90195
24      86837
        ...
9405    87547
9406    87538
9415    87540
9419    87549
9424    87530
Name: Order ID, Length: 2895, dtype: int64

1       20847
5       23597
6       25549
16      22241
24      18181
        ...
9405    21952
9406    22599
9415    26043
9419    24912
9424    25914
Name: Row ID, Length: 2897, dtype: int64

In [155]:
order.dtypes

Row ID                            int64
Order Priority                   object
Discount                        float64
Unit Price                      float64
Shipping Cost                   float64
Customer ID                       int64
Customer Name                    object
Ship Mode                        object
Customer Segment                 object
Product Category                 object
Product Sub-Category             object
Product Container                object
Product Name                     object
Product Base Margin             float64
Region                            int64
State or Province                object
City                             object
Postal Code                       int64
Order Date               datetime64[ns]
Ship Date                datetime64[ns]
Profit                          float64
Quantity ordered new              int64
Sales                           float64
Order ID                          int64
difference_date         timedelta64[ns]
dtype: object

In [172]:
order_returns = pd.merge(order, returns)
order_returns
order_returns.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID', 'difference_date',
       'Status'],
      dtype='object')

In [179]:
#Qstns 10 - Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well 


order_returns[(order_returns['difference_date'].dt.components['days']>15)]

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,difference_date,Status
1,1950,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Seattle,98103,2010-04-04,2010-06-04,112.060000,47,228.46,13959,61 days,Returned
2,1951,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,...,Seattle,98103,2010-04-04,2010-06-04,16.790000,19,77.61,13959,61 days,Returned
8,5257,Low,0.09,550.98,64.59,349,Kim Weiss,Delivery Truck,Home Office,Furniture,...,Miami,33132,2012-09-09,2012-11-09,-1770.965977,76,40136.93,37414,61 days,Returned
9,6643,Critical,0.02,5.98,5.46,349,Kim Weiss,Regular Air,Home Office,Office Supplies,...,Miami,33132,2012-10-12,2012-11-12,-80.903900,62,374.26,47265,31 days,Returned
10,979,Medium,0.01,280.98,57.00,478,Michael Wiggins,Delivery Truck,Small Business,Furniture,...,New York City,10177,2011-08-02,2011-09-02,-416.700000,44,12296.49,7079,31 days,Returned
11,980,Medium,0.03,6.48,5.94,478,Michael Wiggins,Regular Air,Small Business,Office Supplies,...,New York City,10177,2011-08-02,2011-10-02,-34.910000,18,128.13,7079,61 days,Returned
28,7966,High,0.05,7.99,5.03,1060,Gene Gilliam,Regular Air,Small Business,Technology,...,Atlanta,30318,2011-03-02,2011-05-02,-147.090020,34,232.42,56931,61 days,Returned
31,3435,Critical,0.03,5.34,5.63,1106,Maxine Collier Grady,Regular Air,Consumer,Office Supplies,...,Dallas,75220,2012-11-06,2012-12-06,-60.720000,36,208.73,24519,30 days,Returned
43,5883,Low,0.00,9.98,12.52,1228,Hazel Jennings,Regular Air,Small Business,Furniture,...,Philadelphia,19140,2013-01-27,2013-03-02,-213.088000,24,269.95,41760,34 days,Returned
51,5252,Critical,0.08,26.64,5.30,1314,Keith Marsh,Regular Air,Home Office,Furniture,...,Los Angeles,90058,2012-01-04,2012-02-04,90.040000,32,813.66,37380,31 days,Returned
52,5253,Critical,0.00,9.99,4.78,1314,Keith Marsh,Regular Air,Home Office,Office Supplies,...,Los Angeles,90058,2012-01-04,2012-02-04,74.730000,53,571.93,37380,31 days,Returned
53,5254,Critical,0.07,3.55,1.43,1314,Keith Marsh,Regular Air,Home Office,Office Supplies,...,Los Angeles,90058,2012-01-04,2012-02-04,27.370000,47,169.19,37380,31 days,Returned
54,6878,High,0.08,17.67,8.99,1314,Keith Marsh,Regular Air,Home Office,Furniture,...,Los Angeles,90058,2012-11-04,2012-12-04,35.080000,46,795.27,49027,30 days,Returned
55,7626,Critical,0.01,20.24,8.99,1318,Vickie Becker,Regular Air,Home Office,Furniture,...,New York City,10280,2011-04-10,2011-06-10,35.096000,43,938.05,54563,61 days,Returned
58,2771,Not Specified,0.03,150.98,66.27,1723,Constance Flowers,Delivery Truck,Corporate,Furniture,...,San Diego,92037,2011-05-12,2011-08-12,-533.440000,52,8119.28,20036,92 days,Returned
59,2772,Not Specified,0.03,95.99,4.90,1723,Constance Flowers,Regular Air,Corporate,Technology,...,San Diego,92037,2011-05-12,2011-07-12,307.251000,39,3240.93,20036,61 days,Returned
61,2774,Not Specified,0.03,26.31,5.89,1723,Constance Flowers,Regular Air,Corporate,Technology,...,San Diego,92037,2011-05-12,2011-07-12,-25.230000,81,2222.71,20036,61 days,Returned
64,1801,High,0.08,12.64,4.98,1999,Priscilla Kane,Regular Air,Corporate,Furniture,...,Houston,77070,2011-03-05,2011-04-05,100.040000,73,915.60,12900,31 days,Returned
65,1802,High,0.08,306.14,26.53,1999,Priscilla Kane,Delivery Truck,Corporate,Technology,...,Houston,77070,2011-03-05,2011-05-05,308.220000,26,5916.75,12900,61 days,Returned
66,5165,Critical,0.10,7.59,4.00,1999,Priscilla Kane,Regular Air,Home Office,Furniture,...,Houston,77070,2013-08-09,2013-09-09,-10.610000,6,52.26,36743,31 days,Returned
71,1008,High,0.09,16.98,12.39,2189,Frank Cross,Regular Air,Corporate,Office Supplies,...,New York City,10177,2010-08-05,2010-10-05,-48.570000,22,381.91,7364,61 days,Returned
76,6167,Medium,0.05,2.60,2.40,2548,Wayne Bass,Regular Air,Small Business,Office Supplies,...,Los Angeles,90068,2013-07-09,2013-09-09,-17.690000,25,71.69,43713,62 days,Returned
81,1868,High,0.06,4.76,0.88,2645,Ronnie Dodson,Regular Air,Consumer,Office Supplies,...,Seattle,98103,2013-05-01,2013-08-01,21.848000,36,168.48,13444,92 days,Returned
86,998,High,0.03,896.99,19.99,2867,Dana Teague,Regular Air,Corporate,Office Supplies,...,Washington,20016,2013-08-01,2013-10-01,3718.539200,28,24362.25,7203,61 days,Returned
93,986,Not Specified,0.06,37.94,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,Los Angeles,90061,2013-04-01,2013-06-01,-33.968000,3,113.14,7107,61 days,Returned
94,987,Not Specified,0.10,55.29,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,Los Angeles,90061,2013-04-01,2013-05-01,163.120000,35,1886.52,7107,30 days,Returned

In [247]:
#Qstn 11 - Group by region and find out which region is most profitable 
order.groupby(['Region'])['Profit'].aggregate('count').reset_index().sort_values("Profit",ascending = True).max()

Region       0
Profit    9426
dtype: int64

In [243]:
#12. Try to find out overall in which country we are giving more discount 
[order[order['Discount']>0.1]['Region']]

[5990    0
 5991    0
 6000    0
 8649    0
 8661    0
 Name: Region, dtype: int64]

In [239]:
order

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,difference_date
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525,2 days
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2010-07-07,2010-08-07,4.560000,4,13.01,88522,31 days
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523,1 days
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523,1 days
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532,1 days
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532,0 days
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,West Virginia,Charleston,25314,2013-12-09,2013-09-14,-1225.029097,4,2215.93,87533,-86 days
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,Wyoming,Cheyenne,82001,2010-08-02,2010-11-02,349.485000,5,506.50,87530,92 days
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,Wyoming,Cheyenne,82001,2013-12-09,2013-09-14,78.062400,23,172.48,87533,-86 days

In [242]:
#QSTN 13- Give me a list of unique postal code 
order['Postal Code'].unique()

array([60101, 98221, 91776, ..., 61832, 62521, 26554], dtype=int64)

In [245]:
#Qstn 14 - Which customer segement is more profitable find it out . 
order.groupby(['Customer Segment'])['Profit'].aggregate('count')

Customer Segment
Consumer          1894
Corporate         3375
Home Office       2316
Small Business    1841
Name: Profit, dtype: int64

In [249]:
#Qstn 15- try to find out the 10th most loss making product catagory . 
order[order['Profit']<0].reset_index().sort_values('Profit', ascending = True).head(10)

,index,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,difference_date
2291,4659,18306,Medium,0.08,175.99,4.99,1738,Dean Solomon,Regular Air,Corporate,...,North Carolina,Gastonia,28052,2010-03-28,2010-03-28,-16476.83800,10,1486.34,85865,0 days
2121,4338,20972,Low,0.01,24.95,2.99,1632,Lori Wolfe,Regular Air,Home Office,...,Mississippi,Hattiesburg,39401,2012-05-21,2012-05-21,-14369.12358,3,81.31,90534,0 days
3811,7800,23213,Low,0.09,6783.02,24.49,2855,Vicki Womble,Regular Air,Consumer,...,Washington,Des Moines,98198,2010-10-03,2010-03-14,-14140.70160,1,6296.00,87317,-203 days
2381,4844,21284,Critical,0.04,880.98,44.55,1793,Derek Jernigan,Delivery Truck,Home Office,...,Illinois,Galesburg,61401,2010-06-01,2010-07-01,-13706.46400,8,6968.90,87853,30 days
2660,5402,24076,Medium,0.04,6783.02,24.49,2004,James Dickinson Ball,Regular Air,Home Office,...,Montana,Bozeman,59715,2010-10-17,2010-10-19,-13562.63741,1,6569.07,91277,2 days
2664,5409,22942,High,0.05,3502.14,8.73,2006,Cynthia Khan,Delivery Truck,Home Office,...,Colorado,Durango,81301,2011-01-18,2011-01-19,-10402.94392,1,3460.11,88799,1 days
3771,7725,21048,Not Specified,0.06,6783.02,24.49,2825,Carole Rosen,Regular Air,Consumer,...,Idaho,Boise,83701,2011-12-09,2011-09-14,-10263.65970,2,9507.12,89498,-86 days
1061,2191,21575,Not Specified,0.05,3499.99,24.49,838,Gary Walton,Regular Air,Consumer,...,California,Hacienda Heights,91745,2013-02-10,2013-03-10,-9078.94000,2,6849.48,89896,28 days
1977,4068,21917,High,0.06,3502.14,8.73,1530,Seth Sweeney,Delivery Truck,Consumer,...,California,Palm Springs,92262,2012-07-07,2012-09-07,-8570.44830,1,3057.44,88853,62 days
2387,4857,24251,High,0.05,3502.14,8.73,1796,Carlos Johnson,Delivery Truck,Corporate,...,California,San Francisco,94110,2013-03-23,2013-03-24,-7961.43090,1,3360.30,90778,1 days

In [264]:
#Qstn 16 - Try to find out 10 top  product with highest margins 
order.sort_values(['Product Base Margin'])['Product Name'].head(10)

2431              GBC DocuBind 200 Manual Binding Machine
8248       Peel & Seel� Recycled Catalog Envelopes, Brown
1515       Peel & Seel� Recycled Catalog Envelopes, Brown
5050       Peel & Seel� Recycled Catalog Envelopes, Brown
413                                           Accessory31
5034                          Prang Dustless Chalk Sticks
8308         Staples Brown Kraft Recycled Clasp Envelopes
8311     Storex DuraTech Recycled Plastic Frosted Binders
8318                                          Accessory31
1553    Adams Telephone Message Book w/Frequently-Call...
Name: Product Name, dtype: object